### PR TITLE
FB issues added on readme

### PR DESCRIPTION
**Pull request by yxie66**
### Description

Added FB issues to readme.
The ID and secret in providers.json are replaced by my facebook developer account to test on local machine.

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Review by atherdon — COMMENTED** [review]
1) File with credentials must be ignored, in other cases - we'll replace file with my data in your data.
2) your PR is for master branch. don't accepted

**Comment by yxie66** [comment]
1. Is it like keeping the origin account information (yours)?
2. Since we haven't created develop branch, which one should I merge in?

**Comment by atherdon** [comment]
1. Yep for now. it's not very secure, buuuttt as usually. later we'll configure this.
2. i think you can create this branch ;0 just try and we'll see

**Comment by yxie66** [comment]
Can I really create a new one in the "upstream" ?

**Comment by atherdon** [comment]
Let's try and we'll see :0

**Comment by atherdon** [comment]
we can revert this pull request and you'll be able to create a new one

**Comment by yxie66** [comment]
Yes. Having created a new one.

**Pull request closed without merging**
