### PR TITLE
Feature/raven middleware

### PR DESCRIPTION
**Pull request by JorgeRodr**
#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by atherdon** [comment]
i faced an error when i tried to launch a GS with latest updated packages.
did you have a same issue, right?
it's not related to your code, for sure. it's about passport.js update that
broke loopback-passport package

**Comment by JorgeRodr** [comment]
@atherdon I've been resolving conflicts, there was a lot of them.

**Comment by atherdon** [comment]
@JorgeRodr good to know - thank you!
Btw, codacy bot have a lot of suggestions about how we can improve our code. Can you address them too?

**Comment by JorgeRodr** [comment]
@atherdon I have solved most of the codebot issues. Most of them were refering to change singlequote for soublequotes when using strings. Maybe we should use a beautify plugin for our ids. I'm using vscode, maybe you are using another one.

**Comment by JorgeRodr** [comment]
@atherdon well, I think I have screwed it up with the local merge.  I will try to solve it...

**Comment by JorgeRodr** [comment]
@atherdon ok that is what is going on:

When I'm going to push my repo, git adverts me that there is change in the remote repo. I pull the changes and then the grocery.js has a lot of syntax errors. I prefer to wait to your response before make any changes, do you know what happened to that file?

**Comment by atherdon** [comment]
@JorgeRodr i was stuck with some other project that we're working on. hope i didn't slow you down. while i didn't review it - maybe you can work on some other task?

**Pull request closed without merging**
